# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cortex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksGenAI'
  pod 'MediaPipeTasksGenAIC'

  # Pods for cortex

  target 'cortexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cortexUITests' do
    # Pods for testing
  end

end

