import Foundation

struct UserGoals: Codable {
    /// The original, natural language input from the user.
    var rawInput: String
    
    /// The concrete rules generated by our "LLM" for the vision model to check against.
    var verifiableRules: [String]
    
    /// The date the goals were last updated.
    var lastUpdated: Date
}